apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.existingSecret }}
  labels:
    {{- include "metabase.labels" . | nindent 4 }}
type: Opaque
stringData:
  host: {{ .Values.database.host | quote }}
  port: {{ .Values.database.port | quote }}
  dbname: {{ .Values.database.dbname | quote }}
  user: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
